# Generated by Django 3.1.5 on 2021-01-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField()),
                ('paid_to', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=250)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeter.account')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('note', models.CharField(max_length=250)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeter.expense')),
            ],
        ),
    ]
