# Generated by Django 3.1.5 on 2021-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('cash', 'Cash')], default='cash', max_length=30),
            preserve_default=False,
        ),
    ]
