# Generated by Django 3.1.5 on 2021-01-21 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0003_expense_has_expense_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeter.account')),
            ],
        ),
    ]
