# Generated by Django 3.1.5 on 2021-01-21 23:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0005_auto_20210121_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exclude_from_available_funds',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('type', models.CharField(choices=[('D', 'Debit (-)'), ('C', 'Credit (+)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeter.account')),
            ],
        ),
    ]
