# Generated by Django 3.1.5 on 2021-01-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0007_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='from_account',
            new_name='to_account',
        ),
    ]
