# Generated by Django 3.1.5 on 2021-01-22 00:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0009_auto_20210122_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_account', to='budgeter.account'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_account', to='budgeter.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_from_account', to='budgeter.account'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_account', to='budgeter.account'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.CharField(choices=[('D', 'Debit (-)'), ('C', 'Credit (+)')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeter.account')),
            ],
        ),
        migrations.AddField(
            model_name='adjustment',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transaction', to='budgeter.transaction'),
        ),
    ]
