# Generated by Django 3.1.5 on 2021-01-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0010_auto_20210122_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_transaction', to='budgeter.transaction'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transaction', to='budgeter.transaction'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_transaction', to='budgeter.transaction'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_transaction', to='budgeter.transaction'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transaction', to='budgeter.transaction'),
        ),
    ]
