# Generated by Django 3.1.5 on 2021-01-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0011_auto_20210122_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='transaction',
        ),
    ]
