# Generated by Django 3.1.5 on 2021-01-22 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0012_remove_withdrawal_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transaction', to='budgeter.transaction'),
        ),
    ]
