# Generated by Django 3.1.5 on 2021-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0015_auto_20210122_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('X', 'Expense'), ('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer'), ('AC', 'Adjustment - Credit'), ('AD', 'Adjustment - Debit')], max_length=10),
        ),
    ]
