# Generated by Django 3.1.5 on 2021-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0016_auto_20210122_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ledger_type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('Z', 'Unknown')], default='Z', max_length=10),
        ),
    ]
