# Generated by Django 3.1.5 on 2021-01-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0017_transaction_ledger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
