# Generated by Django 3.1.5 on 2021-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0018_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recurring_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_expense_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
