# Generated by Django 3.1.5 on 2021-01-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0019_auto_20210128_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recurring_expense_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
