# Generated by Django 3.1.5 on 2021-01-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0020_auto_20210128_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='recurring_expense_date',
        ),
    ]
