# Generated by Django 3.1.5 on 2021-01-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0021_remove_expense_recurring_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring_expense_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
