# Generated by Django 3.1.5 on 2021-03-05 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0022_expense_recurring_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_recurring_expense',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurring_expense_date',
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_day', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid_to', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('has_expense_items', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expense_from_account', to='budgeter.account')),
                ('transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expense_transaction', to='budgeter.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_expense',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.recurringexpense'),
        ),
    ]
