# Generated by Django 3.1.5 on 2021-03-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0023_auto_20210305_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_recurring_expense',
            field=models.BooleanField(default=False),
        ),
    ]
