# Generated by Django 3.1.5 on 2021-03-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0025_auto_20210306_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringexpense',
            name='has_expense_items',
        ),
    ]
