# Generated by Django 3.1.5 on 2021-03-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0027_remove_expense_is_recurring_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_from_account', to='budgeter.account'),
        ),
    ]
