# Generated by Django 3.1.5 on 2021-03-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0028_auto_20210307_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='debit_from_account',
            field=models.BooleanField(default=False),
        ),
    ]
