# Generated by Django 3.1.5 on 2021-03-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0029_expense_debit_from_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
