# Generated by Django 3.1.5 on 2021-03-08 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0030_auto_20210308_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.CharField(choices=[('X', 'Expense'), ('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer'), ('AC', 'Adjustment - Credit'), ('AD', 'Adjustment - Debit')], max_length=10)),
                ('ledger_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('Z', 'Unknown')], default='Z', max_length=10)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.account')),
            ],
        ),
        migrations.AddField(
            model_name='adjustment',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_transaction', to='budgeter.transaction'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_transaction', to='budgeter.transaction'),
        ),
    ]
