# Generated by Django 3.1.5 on 2021-03-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0032_auto_20210309_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='has_expense_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('X', 'Expense'), ('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer'), ('A', 'Adjustment - Credit'), ('AD', 'Adjustment - Debit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='ledger_type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='type',
            field=models.CharField(choices=[('X', 'Expense'), ('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer'), ('AC', 'Adjustment')], max_length=10),
        ),
    ]
