# Generated by Django 3.1.5 on 2021-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0033_auto_20210309_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='has_expense_items',
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='has_expense_items',
            field=models.BooleanField(default=False),
        ),
    ]
