# Generated by Django 3.1.5 on 2021-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0034_auto_20210309_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='description',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
