# Generated by Django 3.1.5 on 2021-03-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0035_transactionrecord_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='category',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('groceries', 'Groceries'), ('gas', 'Gas')], default=None, max_length=200, null=True),
        ),
    ]
