# Generated by Django 3.1.5 on 2021-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0036_transactionrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
