# Generated by Django 3.1.5 on 2021-03-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0038_auto_20210310_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.creditcard'),
        ),
    ]
