# Generated by Django 3.1.5 on 2021-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0040_auto_20210311_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='sub_category',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
