# Generated by Django 3.1.5 on 2021-03-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0041_transactionrecord_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='exclude_from_accounting',
            field=models.BooleanField(default=False),
        ),
    ]
