# Generated by Django 3.1.5 on 2021-03-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0042_transactionrecord_exclude_from_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
