# Generated by Django 3.1.5 on 2021-03-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0043_auto_20210312_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
