# Generated by Django 3.1.5 on 2021-03-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0044_auto_20210316_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgeter.account')),
                ('credit_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgeter.creditcard')),
            ],
        ),
    ]
