# Generated by Django 3.1.5 on 2021-03-19 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0045_creditcardpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='credit_card',
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='account_tr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountTR', to='budgeter.account'),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='credit_card_tr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditCardTR', to='budgeter.creditcard'),
        ),
    ]
