# Generated by Django 3.1.5 on 2021-03-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0046_auto_20210319_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardpayment',
            name='account_tr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountTR', to='budgeter.transactionrecord'),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='credit_card_tr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditCardTR', to='budgeter.transactionrecord'),
        ),
    ]
