# Generated by Django 3.1.5 on 2021-03-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0047_auto_20210319_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountFrom', to='budgeter.transactionrecord')),
                ('account_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountTo', to='budgeter.transactionrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='CreditCardPayment',
        ),
    ]
