# Generated by Django 3.1.5 on 2021-03-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0048_auto_20210321_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferaccounts',
            name='account_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountFrom', to='budgeter.account'),
        ),
        migrations.AlterField(
            model_name='transferaccounts',
            name='account_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountTo', to='budgeter.account'),
        ),
    ]
