# Generated by Django 3.1.5 on 2021-03-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0049_auto_20210321_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferaccounts',
            name='account_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountFrom', to='budgeter.account'),
        ),
        migrations.AlterField(
            model_name='transferaccounts',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountTo', to='budgeter.account'),
        ),
    ]
