# Generated by Django 3.1.5 on 2021-03-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0050_auto_20210321_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferaccounts',
            name='account_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountFromTR', to='budgeter.transactionrecord'),
        ),
        migrations.AlterField(
            model_name='transferaccounts',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountToTR', to='budgeter.transactionrecord'),
        ),
    ]
