# Generated by Django 3.1.5 on 2021-03-29 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0052_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionrecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.category'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeter.subcategory'),
        ),
    ]
