# Generated by Django 3.1.5 on 2021-03-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0053_auto_20210329_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
