# Generated by Django 3.1.5 on 2021-03-30 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0055_auto_20210329_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountPaidFrom', to='budgeter.transactionrecord')),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditCardPaidTo', to='budgeter.transactionrecord')),
            ],
        ),
    ]
